on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
      - uses: actions/checkout@v2
      - name: install & run csharpier
        run: |
          dotnet tool install -g csharpier
          dotnet csharpier