on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
      - uses: actions/checkout@v2
      - run: dotnet build --configuration Release
      - run: |
          cd ${{ github.workspace }}/mongo-declarative-indexes.Tests
          dotnet test --configuration Release --no-build
        